export const voices = [
  {
    language: "Arabic",
    lanCode: "arb",
    id: "Zeina",
    sex: "F",
  },

  {
    language: "Mandarin",
    lanCode: "cmn-CN",
    id: "Zhiyu",
    sex: "F",
  },
  {
    language: "Danish",
    lanCode: "da-DK",
    id: "Naja",
    sex: "F",
  },
  {
    language: "Danish",
    lanCode: "da-DK",
    id: "Mads",
    sex: "M",
  },
  {
    language: "Dutch",
    lanCode: "nl-NL",
    id: "Ruben",
    sex: "M",
  },
  {
    language: "Dutch",
    lanCode: "nl-NL",
    id: "Zeina",
    sex: "F",
  },
  {
    language: "English (Australian)",
    lanCode: "en-AU",
    id: "Nicole",
    sex: "F",
  },
  {
    language: "English (Australian)",
    lanCode: "en-AU",
    id: "Olivia",
    sex: "F",
  },
  {
    language: "English (Australian)",
    lanCode: "en-AU",
    id: "Russell",
    sex: "M",
  },
  {
    language: "English (British)",
    lanCode: "en-GB",
    id: "Amy",
    sex: "F",
  },
  {
    language: "English (British)",
    lanCode: "en-GB",
    id: "Emma",
    sex: "F",
  },
  {
    language: "English (British)",
    lanCode: "en-GB",
    id: "Brian",
    sex: "M",
  },
  {
    language: "English (Indian)",
    lanCode: "en-IN",
    id: "Aditi",
    sex: "F",
  },
  {
    language: "English (Indian)",
    lanCode: "en-IN",
    id: "Raveena",
    sex: "F",
  },
  {
    language: "English (New Zealand)",
    lanCode: "en-NZ",
    id: "Aria",
    sex: "F",
  },
  {
    language: "English (South African)",
    lanCode: "en-ZA",
    id: "Ayanda",
    sex: "F",
  },
  {
    language: "English (US)",
    lanCode: "en-US",
    id: "Ivy",
    sex: "F",
  },
  {
    language: "English (US)",
    lanCode: "en-US",
    id: "Joanna",
    sex: "F",
  },
  {
    language: "English (US)",
    lanCode: "en-US",
    id: "Kendra",
    sex: "F",
  },
  {
    language: "English (US)",
    lanCode: "en-US",
    id: "Kimberly",
    sex: "F",
  },
  {
    language: "English (US)",
    lanCode: "en-US",
    id: "Salli",
    sex: "F",
  },
  {
    language: "English (US)",
    lanCode: "en-US",
    id: "Joey",
    sex: "M",
  },
  {
    language: "English (US)",
    lanCode: "en-US",
    id: "Justin",
    sex: "M",
  },
  {
    language: "English (US)",
    lanCode: "en-US",
    id: "Kevin",
    sex: "M",
  },
  {
    language: "English (US)",
    lanCode: "en-US",
    id: "Matthew",
    sex: "M",
  },
  {
    language: "English (Welsh)",
    lanCode: "en-GB-WLS",
    id: "Geraint",
    sex: "M",
  },
  {
    language: "French",
    lanCode: "fr-FR",
    id: "Céline",
    sex: "F",
  },
  {
    language: "French",
    lanCode: "fr-FR",
    id: "Léa",
    sex: "F",
  },
  {
    language: "French",
    lanCode: "fr-FR",
    id: "Mathieu",
    sex: "M",
  },
  {
    language: "French (Canadian)",
    lanCode: "fr-CA",
    id: "Chantal",
    sex: "F",
  },
  {
    language: "French (Canadian)",
    lanCode: "fr-CA",
    id: "Gabrielle",
    sex: "F",
  },
  {
    language: "German",
    lanCode: "de-DE",
    id: "Marlene",
    sex: "F",
  },
  {
    language: "German",
    lanCode: "de-DE",
    id: "Vicki",
    sex: "F",
  },
  {
    language: "German",
    lanCode: "de-DE",
    id: "Hans",
    sex: "M",
  },
  {
    language: "Hindi",
    lanCode: "hi-IN",
    id: "Aditi",
    sex: "F",
  },

  {
    language: "Icelandic",
    lanCode: "is-IS",
    id: "Dóra",
    sex: "F",
  },
  {
    language: "Icelandic",
    lanCode: "is-IS",
    id: "Karl",
    sex: "M",
  },
  {
    language: "Italian",
    lanCode: "it-IT",
    id: "Carla",
    sex: "F",
  },
  {
    language: "Italian",
    lanCode: "it-IT",
    id: "Bianca",
    sex: "F",
  },
  {
    language: "Italian",
    lanCode: "it-IT",
    id: "Giorgio",
    sex: "M",
  },
  {
    language: "Japanese",
    lanCode: "ja-JP",
    id: "Mizuki",
    sex: "F",
  },
];
